from ._align import CellAlignDTW
from ._gam import gam_smooth_expression
from ._cluster import process_gene_data, enrichr, order_genes
from ._sliding_window import perform_sliding_window_enrichr_analysis, pivot_results, calculate_significant_gene_sets, calculate_max_position, plot_heatmap, analyze_and_plot_enrichment, sliding_window_enrichment, permutation_test_with_nes, compute_enrichment_signals, plot_enrichment_signals
from ._dba import dtw_barycenter_averaging_with_categories